server:
  port: 9052
  
security:
  sessions: never
logging:
  level:
    org.springframework.web: INFO
    org.springframework.session: INFO
    org.springframework.security: ERROR
    com.hazelcast: INFO
    logging.level.org.hibernate: ERROR
  file: clinicalweb.log

spring:
  profiles:
    active: development,oracle
  thymeleaf:
    prefix: classpath:/public/
    cache: false
  mvc:
    locale: pt_BR
    
cluster:
  group:
    name: desenv
    
---

spring:
  profiles: tests
  session:
    store-type: none
  datasource:
    url: jdbc:h2:mem:mydb;INIT=CREATE SCHEMA IF NOT EXISTS dap;DB_CLOSE_ON_EXIT=FALSE;Mode=Oracle;
  jpa: 
    database-platform: org.hibernate.dialect.Oracle10gDialect